accounts/urls.py
from django.urls import path
from .views import UserRegistrationView, UserLoginView, UserLogOutView, UserBankAccountView, UserBankAccountUpdateView

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogOutView.as_view(), name='logout'),
    path('profile/', UserBankAccountView.as_view(), name='profile'),
    path('edit-profile/', UserBankAccountUpdateView.as_view(), name='edit_profile'),
]

state_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
    path('admin/', admin.site.urls),
]

transactions/urls.py
from django.urls import path
from .views import DepositMoneyView, WithdrawMoneyView, TransactionStatementView, TransferMoneyView, LoanRequestView, LoanListView, LoanRepaymentView

urlpatterns = [
    path('deposit/', DepositMoneyView.as_view(), name='deposit'),
    path('withdraw/', WithdrawMoneyView.as_view(), name='withdraw'),
    path('statements/', TransactionStatementView.as_view(), name='statements'),
    path('transfer/', TransferMoneyView.as_view(), name='transfer'),
    path('loan-request/', LoanRequestView.as_view(), name='loan_request'),
    path('loans/', LoanListView.as_view(), name='loan_list'),    
    path('loan-repay/<int:loan_id>/', LoanRepaymentView.as_view(), name='loan_repay'),
]

transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from .constants import TRANSACTION_TYPE

# Create your models here.
class Transaction(models.Model):
    account = models.ForeignKey(UserBankAccount, related_name='transactions', on_delete=models.CASCADE)
    recipient_account_no = models.CharField(max_length=100, null=True, blank=True)
    sender = models.ForeignKey(UserBankAccount, related_name='transfer_sender', on_delete=models.CASCADE, null=True, blank=True)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    balance_after_transaction = models.DecimalField(max_digits=12, decimal_places=2)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    loan_approval = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['timestamp']
        
        
class Bank(models.Model):
    isBankrupt = models.BooleanField(default=False)
    
    def __str__(self):
        return "Bank Status"

transactions/forms.py
from django import forms
from .models import Transaction
from django.contrib.auth.models import User
from accounts.models import UserBankAccount
from .models import Bank


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'transaction_type']
        
    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()
        
    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()
        
class DepositForm(TransactionForm):
    def clean_amount(self):
        min_deposit_amount = 500
        amount = self.cleaned_data.get('amount')
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f"You need to deposit at least $ {min_deposit_amount}"
            )
        return amount
    
class WithdrawForm(TransactionForm):
    def clean_amount(self):
        bank = Bank.objects.first()
        if bank and bank.isBankrupt:
            raise forms.ValidationError("The Bank is Bankrupt!")
            
        account = self.account
        min_withdrawal_amount = 500
        max_withdrawal_amount = 1000000
        balance = account.balance
        amount = self.cleaned_data.get('amount')
        if amount > balance:
            raise forms.ValidationError(
                f"You have insufficient balance!"
            )
        if amount < min_withdrawal_amount:
            raise forms.ValidationError(
                f"You can withdraw at least $ {min_withdrawal_amount}"
            )
        if amount > max_withdrawal_amount:
            raise forms.ValidationError(
                f"You can withdraw at most $ {max_withdrawal_amount}"
            )
        return amount
    
class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        return amount
    
class TransferTransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['recipient_account_no', 'amount', 'transaction_type']
       
    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()
        bank = Bank.objects.first()
        if bank and bank.isBankrupt:
            self.add_error(None, "The Bank is Bankrupt")
        
    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()
    
class TransferMoneyForm(TransferTransactionForm):
    def clean_amount(self):
        account = self.account
        min_transfer_amount = 500
        max_transfer_amount = 1000000
        balance = account.balance
        amount = self.cleaned_data.get('amount')
        bank = Bank.objects.first()
        
        if bank and bank.isBankrupt:
            raise forms.ValidationError("The Bank is Bankrupt!")        
        if amount > balance:
            raise forms.ValidationError(
                f"You have insufficient balance!"
            )
        if amount < min_transfer_amount:
            raise forms.ValidationError(
                f"You have to transfer at least $ {min_transfer_amount}"
            )
        if amount > max_transfer_amount:
            raise forms.ValidationError(
                f"You can transfer at most $ {max_transfer_amount}"
            )        
        return amount
    
    def clean_recipient_account(self):
        recipient_account_no = self.cleaned_data.get('recipient_account_no')
        
        if len(str(recipient_account_no)) != 10:
            raise forms.ValidationError(
                "The account number must be exactly 10 digits."
            )
        if not UserBankAccount.objects.filter(account_no=recipient_account_no).exists():
            raise forms.ValidationError(
                f"There is no account with the account no {recipient_account_no}!"
            )
        return recipient_account_no
              

transactions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, ListView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Sum
from django.urls import reverse_lazy
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.forms import ValidationError
from .models import Transaction
from .forms import DepositForm, WithdrawForm, LoanRequestForm, TransferMoneyForm
from .constants import DEPOSIT, WITHDRAW, TRANSFER1, TRANSFER2, LOAN_REQUEST, LOAN_REPAY
from accounts.models import UserBankAccount

# Create your views here.
class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transactions/transaction_form.html'
    model = Transaction
    title = ''
    key = ''
    success_url = reverse_lazy('statements')
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': self.title,
            'key': self.key
        })
        return context
    
class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit Money'
    key = 'Deposit'
    
    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial
    
    def form_valid(self, form):  
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance += amount
        account.save(
            update_fields = ['balance']
        )
        messages.success(self.request, f"${'{:,.2f}'.format(float(amount))} deposited successfully!")
        return super().form_valid(form)
    
class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw Money'
    key = 'Withdraw'
    
    def get_initial(self):
        initial = {'transaction_type': WITHDRAW}
        return initial
    
    def form_valid(self, form):        
        account = self.request.user.account
        amount = form.cleaned_data.get('amount')
        account.balance -= amount
        account.save(
            update_fields = ['balance']
        )
        messages.success(self.request, f"${'{:,.2f}'.format(float(amount))}  withdrawn successfully!")
        return super().form_valid(form)
    
class LoanRequestView(TransactionCreateMixin):
    form_class = LoanRequestForm
    title = 'Apply for a Loan'
    key = 'Loan'
    
    def get_initial(self):
        initial = {'transaction_type': LOAN_REQUEST}
        return initial
    
    def form_valid(self, form):        
        amount = form.cleaned_data.get('amount')
        current_loan_count = Transaction.objects.filter(account = self.request.user.account, transaction_type = LOAN_REQUEST, loan_approval = True).count()
        if current_loan_count >= 3:
            return HttpResponse("You have exceeded your loan limit!")
        messages.success(self.request, f"You Loan application has been submitted! Your Requested Loan Amount is ${'{:,.2f}'.format(float(amount))}")
        return super().form_valid(form)
    
class TransactionStatementView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_statements.html'
    model = Transaction
    balance = 0
    
    def get_queryset(self):
        queryset= super().get_queryset().filter(
            account = self.request.user.account
        )
        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')
        
        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()
            queryset = queryset.filter(timestamp__date__gte=start_date, timestamp__date__lte=end_date)
            self.balance = Transaction.objects.filter(timestamp__date__gte=start_date, timestamp__date__lte=end_date).aggregate(Sum('amount'))['amount__sum']
        else:
            self.balance = self.request.user.account.balance
            
        queryset = queryset.order_by('-timestamp')
        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account': self.request.user.account
        })
        return context
    
class LoanRepaymentView(LoginRequiredMixin, View):
    def get(self, request, loan_id):
        loan = get_object_or_404(Transaction, id=loan_id)
        if loan.loan_approval():
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -=loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.transaction_type = LOAN_REPAY
                loan.save()
                return redirect('loan_list')
            else:
                messages.error(self.request, f"You have insufficient balance to Loan Repayment!")
                return redirect('loan_list')
            
class LoanListView(LoginRequiredMixin, ListView):
    template_name = 'transactions/loan_list.html'
    model = Transaction
    context_object_name = 'loans'
    
    def get_queryset(self):
        user_account = self.request.user.account
        queryset = Transaction.objects.filter(account=user_account, transaction_type=LOAN_REQUEST)
        return queryset

class TransferMoneyView(TransactionCreateMixin):
    form_class = TransferMoneyForm
    title = 'Transfer Money'
    key = 'Transfer'
    
    def get_initial(self):
        initial = {'transaction_type': TRANSFER1}
        return initial
    
    def form_valid(self, form):        
        user_account = self.request.user.account
        recipient_account_no = form.cleaned_data.get('recipient_account_no')
        amount = form.cleaned_data.get('amount')
        
        try:
            recipient = UserBankAccount.objects.get(account_no=recipient_account_no)
        except UserBankAccount.DoesNotExist:
            form.add_error('recipient_account_no', f"There is no account with the account number {recipient_account_no}.")
            return self.form_invalid(form)
            
        user_account.balance -= amount
        recipient.balance += amount
        
        user_account.save(
            update_fields = ['balance']
        )
        recipient.save(
            update_fields = ['balance']
        )        
        Transaction.objects.create(
            account=recipient,
            sender=user_account,
            amount=amount,
            balance_after_transaction=recipient.balance,
            transaction_type=TRANSFER2 
        )
        messages.success(self.request, f"${amount} transferred to account successfully!")
        return super().form_valid(form)
                
    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))   

transactions/templates/transactions/email_template.html
<div>
    <h3>Hello, {{user.first_name}} {{user.last_name}}</h3>

    <p>I hope this email finds you well.</p>

    {% if key == 'Loan Approval' %}
    <p>We are pleased to inform you that your Loan Application has been successfully approved. The requested amount of ${{amount}} will be credited to your account shortly.</p>
    {% elif key == 'Loan' %}
    <p>This is to confirm that we have received your {{key}} request for an amount of ${{amount}}. Our team is now processing your request and will get back to you shortly with further details.</p>
    {% else %}
    <p>We are writing to confirm that your recent {{key}} of ${{amount}} has been successfully processed. Your updated account balance is now ${{balance}}.</p>
    {% endif %}

    <p>For any query you can replay in to this email.</p>

    {% if key == 'Loan Approval' %}
    <p>Congratulations on your approval, and thank you for banking with us!</p>
    {% else %}
    <p>Thank you for banking with us!</p>
    {% endif %}

    <p>Best Regards</p>
    <p>State Bank</p>
</div>

transactions/templates/transactions/loan_list.html
{% extends 'base.html' %} 
{% block page__title %} {{ title }} {% endblock %} 

{% block content %}
<div class="text-white">
    <div class="container mx-auto p-5">
        <div class="mt-10 mb-8 flex justify-center items-center">
            <h1 class="text-4xl font-bold text-center">Loan Lists</h1>
        </div>
        <div class="overflow-x-auto">
            <table class="table-auto w-full">
                <thead>
                    <tr>
                        <th class="border p-3">Loan ID</th>
                        <th class="border p-3">Application Date</th>
                        <th class="border p-3">Amount</th>
                        <th class="border p-3">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for loan in loans %}
                        <tr>
                            <td class="border p-3 text-center">{{loan.id}}</td>
                            <td class="border p-3 text-center">{{loan.timestamp|date:"F d, Y h:i A"}}</td>
                            <td class="border p-3 text-center">{{loan.amount}}</td>
                            <td class="border p-3 text-center">
                                {% if loan.loan_approval %} <a href="{% url 'loan_repay' loan.id %}" class="bg-gray-900 px-5 py-2 rounded-md">Loan Repay</a> {% else %} Pending {% endif%}
                            </td>                           
                        </tr>
                    {% endfor %}                        
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

transactions/templates/transactions/transaction_form.html
{% extends 'base.html' %}
{% block page_title %} {{title}} - State Bank {% endblock %}

{% block content %}
<div class="text-white">
    <div class="container mx-auto p-5">
        <div class="mt-16 mb-8 flex justify-center items-center">
            <h1 class="text-4xl font-bold text-center">{{title}}</h1>
        </div>
        <div class="bg-slate-900 rounded-xl w-full md:w-[80%] lg:w-[60%] xl:w-[40%] mt-10 mx-auto p-8 py-10">
            <form method="post">
                {% csrf_token %}
                {% if key == 'Transfer' %}
                <div class="w-full mb-5">
                    <label class="text-lg uppercase font-semibold tracking-wide px-1 mb-2" for="recipient_account_no">Recipient Account No</label>
                    <input class="shadow appearance-none border border-gray-500 rounded w-full py-2.5 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mt-2 font-bold" name="recipient_account_no" id="recipient_account_no" type="number" placeholder="Recipient Account No" minlength="10" maxlength="10" required>
                </div>
                <div>
                    {% if form.recipient_account_no.errors %}
                        {% for error in form.recipient_account_no.errors %}
                            <div class="bg-red-600 text-white px-5 py-3 rounded-xl font-semibold flex items-center flex-wrap gap-3 my-5">
                                <span class="text-lg">&#9888;</span>
                                <span>{{error}}</span>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div> 
                {% endif %}
                <div class="w-full mb-5">
                    <label class="text-lg uppercase font-semibold tracking-wide px-1 mb-2" for="amount">{{key}} Amount</label>
                    <input class="shadow appearance-none border border-gray-500 rounded w-full py-2.5 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mt-2 font-bold" name="amount" id="amount" type="number" placeholder="Enter Amount" required>
                </div> 
                <div>
                    {% if form.amount.errors %}
                        {% for error in form.amount.errors %}
                            <div class="bg-red-600 text-white px-5 py-3 rounded-xl font-semibold flex items-center flex-wrap gap-3 mt-5">
                                <span class="text-lg">&#9888;</span>
                                <span>{{error}}</span>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div> 
                <div class="flex justify-center mt-8 gap-x-4">
                    <button type="submit" class="bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-8 rounded focus:outline-none focus:shadow-outline tracking-wide">{{key}}</button>                 
                    {% if title == 'Apply for a Loan' %}
                        <a href={% url 'loan_list' %} class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-8 rounded focus:outline-none focus:shadow-outline tracking-wide">Loan List</a>
                    {% endif %} 
                </div>                  
            </form>
        </div>
    </div>        
</div>
{% endblock %}

transactions/templates/transactions/transaction_statements.html
{% extends 'base.html' %}
{% load humanize %}
{% block page_title %} Transaction Statements - State Bank {% endblock %}

{% block content %}
<div class="text-white">
    <div class="container mx-auto p-5">
        <div class="mt-10 mb-8 flex justify-center items-center">
            <h1 class="text-4xl font-bold text-center">Transaction Statements</h1>
        </div>        
        <form method="get" action="{% url 'statements' %}">
            <div class="w-full flex flex-wrap items-center gap-5 mt-12 mb-5">                
                <div class="px-4 bg-white rounded-md flex justify-between items-center relative text-black py-2 gap-x-2 w-full sm:w-1/2 lg:w-1/3 xl:w-1/4">
                    <label for="start_date" class="font-semibold">From:</label>
                    <input class="appearance-none w-full outline-none focus:outline-none active:outline-none" type="date" id="start_date" name="start_date" />
                </div>
                <div class="px-4 bg-white rounded-md flex justify-between items-center relative text-black py-2 gap-x-2 w-full sm:w-1/2 lg:w-1/3 xl:w-1/4">
                    <label for="end_date" class="font-semibold">To:</label>
                    <input class="appearance-none w-full outline-none focus:outline-none active:outline-none" type="date" id="end_date" name="end_date" />
                </div>
                <div>
                    <button class="px-8 py-2 bg-gray-900 tracking-wide appearance-none w-full outline-none focus:outline-none active:outline-none rounded-md">Filter</button>
                </div>
            </div>
            <div class="overflow-x-auto">
                <table class="table-auto w-full">
                    <thead>
                        <tr>
                            <th class="border p-3">Transaction Date</th>
                            <th class="border p-3">Transaction Type</th>
                            <th class="border p-3">Transaction Amount</th>
                            <th class="border p-3">New Balance</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for transaction in object_list %}
                            <tr>
                                <td class="border p-3 text-center">{{transaction.timestamp|date:"F d, Y h:i A"}}</td>
                                <td class="border p-3 text-center {% if transaction.get_transaction_type_display == 'Withdraw' %} text-red-400 {% elif transaction.get_transaction_type_display == 'Sent' %} text-red-400 {% else %} text-green-400 {% endif %}">{{transaction.get_transaction_type_display}}</td>
                                <td class="border p-3 text-center {% if transaction.get_transaction_type_display == 'Withdraw' %} text-red-400 {% elif transaction.get_transaction_type_display == 'Sent' %} text-red-400 {% else %} text-green-400 {% endif %}">{% if transaction.get_transaction_type_display == 'Withdraw' %} - {% elif transaction.get_transaction_type_display == 'Sent' %} - {% else %} + {% endif %} $ {{transaction.amount|floatformat:2|intcomma}}</td>
                                <td class="border p-3 text-center">$ {{transaction.balance_after_transaction|floatformat:2|intcomma}}</td>
                            </tr>
                        {% endfor %}                        
                    </tbody>
                </table>
                <div>
                    <div class="w-full flex justify-between items-center py-4 px-6 border text-lg font-semibold tracking-wide">
                        <span>Current Balance:</span>
                        <span>$ {{account.balance|floatformat:2|intcomma}}</span>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}